language: ruby
rvm:
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
  - "1.9.2"
before_install: 
  - sudo apt-get install -qq libzmq-dev
# after_failure: "cat /home/travis/.rvm/gems/ruby-2.0.0-rc1/gems/zmq-2.1.4/./gem_make.out"
# after_script: "cat /home/travis/.rvm/gems/ruby-2.0.0-rc1/gems/zmq-2.1.4/./gem_make.out"
