language: ruby
rvm:
- "jruby-9.0.5.0"
- "jruby-9.1.17.0"
before_install: 
  - sudo apt-get install -qq libzmq3-dev
# after_failure: "cat /home/travis/.rvm/gems/ruby-2.0.0-rc1/gems/zmq-2.1.4/./gem_make.out"
# after_script: "cat /home/travis/.rvm/gems/ruby-2.0.0-rc1/gems/zmq-2.1.4/./gem_make.out"
